//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameTech.Elite.Client.Modules.SessionSummary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameTech.Elite.Client.Modules.SessionSummary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Accrual Increases and Reseed.
        /// </summary>
        internal static string Acc2TriggerIncreasesAndReseed {
            get {
                return ResourceManager.GetString("Acc2TriggerIncreasesAndReseed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Activate.
        /// </summary>
        internal static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calc_ulate.
        /// </summary>
        internal static string Calculate {
            get {
                return ResourceManager.GetString("Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your changes will be lost..
        /// </summary>
        internal static string ChangedCantSave {
            get {
                return ResourceManager.GetString("ChangedCantSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application is currently busy, do you really wish to exit?.
        /// </summary>
        internal static string ConfirmExit {
            get {
                return ResourceManager.GetString("ConfirmExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cost has been changed.
        ///Would you like to save these changes?.
        /// </summary>
        internal static string CostChanged {
            get {
                return ResourceManager.GetString("CostChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create the user interface.
        ///Reason: {0}.
        /// </summary>
        internal static string CreateUIFailed {
            get {
                return ResourceManager.GetString("CreateUIFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Deactivate.
        /// </summary>
        internal static string Deactivate {
            get {
                return ResourceManager.GetString("Deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Generate.
        /// </summary>
        internal static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve the currencies from the server.
        ///Reason: {0}.
        /// </summary>
        internal static string GetCurrenciesFailed {
            get {
                return ResourceManager.GetString("GetCurrenciesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve the machine id.
        ///Reason: {0}.
        /// </summary>
        internal static string GetDeviceInfoFailed {
            get {
                return ResourceManager.GetString("GetDeviceInfoFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve the exchange rates from the server.
        ///Reason: {0}.
        /// </summary>
        internal static string GetExchangeRatesFailed {
            get {
                return ResourceManager.GetString("GetExchangeRatesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve the operator data from the server..
        /// </summary>
        internal static string GetOperatorDataFailed {
            get {
                return ResourceManager.GetString("GetOperatorDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve this machine&apos;s information from the server.
        ///Reason: {0}.
        /// </summary>
        internal static string GetSettingsFailed {
            get {
                return ResourceManager.GetString("GetSettingsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit cannot be negative.
        /// </summary>
        internal static string InvalidBankDepositTotal {
            get {
                return ResourceManager.GetString("InvalidBankDepositTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid name.
        /// </summary>
        internal static string InvalidCostName {
            get {
                return ResourceManager.GetString("InvalidCostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid value.
        /// </summary>
        internal static string InvalidCostValue {
            get {
                return ResourceManager.GetString("InvalidCostValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid gaming date.
        /// </summary>
        internal static string InvalidGamingDate {
            get {
                return ResourceManager.GetString("InvalidGamingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid attendance.
        /// </summary>
        internal static string InvalidManualAttendance {
            get {
                return ResourceManager.GetString("InvalidManualAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid session.
        /// </summary>
        internal static string InvalidSelectedSession {
            get {
                return ResourceManager.GetString("InvalidSelectedSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid value.
        /// </summary>
        internal static string InvalidValue {
            get {
                return ResourceManager.GetString("InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving banks.
        /// </summary>
        internal static string LoadingBanks {
            get {
                return ResourceManager.GetString("LoadingBanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading application controllers.
        /// </summary>
        internal static string LoadingControllers {
            get {
                return ResourceManager.GetString("LoadingControllers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the application controllers.
        ///Reason: {0}.
        /// </summary>
        internal static string LoadingControllersFailed {
            get {
                return ResourceManager.GetString("LoadingControllersFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving list of available currencies..
        /// </summary>
        internal static string LoadingCurrencyInformation {
            get {
                return ResourceManager.GetString("LoadingCurrencyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving this machine&apos;s information.
        /// </summary>
        internal static string LoadingMachineInfo {
            get {
                return ResourceManager.GetString("LoadingMachineInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Operator Data.
        /// </summary>
        internal static string LoadingOperatorData {
            get {
                return ResourceManager.GetString("LoadingOperatorData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading session summary report.
        /// </summary>
        internal static string LoadingReport {
            get {
                return ResourceManager.GetString("LoadingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the session summary report.
        ///Reason: {0}.
        /// </summary>
        internal static string LoadingReportFailed {
            get {
                return ResourceManager.GetString("LoadingReportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading resources.
        /// </summary>
        internal static string LoadingResources {
            get {
                return ResourceManager.GetString("LoadingResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving sessions.
        /// </summary>
        internal static string LoadingSessions {
            get {
                return ResourceManager.GetString("LoadingSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve the session list from the server.
        ///Reason: {0}.
        /// </summary>
        internal static string LoadingSessionsFailed {
            get {
                return ResourceManager.GetString("LoadingSessionsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving staff list.
        /// </summary>
        internal static string LoadingStaff {
            get {
                return ResourceManager.GetString("LoadingStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve the staff list from the server.
        ///Reason: {0}.
        /// </summary>
        internal static string LoadingStaffFailed {
            get {
                return ResourceManager.GetString("LoadingStaffFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find your staff information..
        /// </summary>
        internal static string LoadingStaffFailedCurrentNotFound {
            get {
                return ResourceManager.GetString("LoadingStaffFailedCurrentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No staff found..
        /// </summary>
        internal static string LoadingStaffFailedNoStaffFound {
            get {
                return ResourceManager.GetString("LoadingStaffFailedNoStaffFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving summary.
        /// </summary>
        internal static string LoadingSummary {
            get {
                return ResourceManager.GetString("LoadingSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve session summary.
        /// </summary>
        internal static string LoadingSummaryFailed {
            get {
                return ResourceManager.GetString("LoadingSummaryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load Session Summary&apos;s resource dictionaries.
        ///Reason: {0}.
        /// </summary>
        internal static string LoadResourceDictionariesFailed {
            get {
                return ResourceManager.GetString("LoadResourceDictionariesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create the log.
        ///Reason: {0}.
        /// </summary>
        internal static string LogFailed {
            get {
                return ResourceManager.GetString("LogFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lose Changes.
        /// </summary>
        internal static string LoseChanges {
            get {
                return ResourceManager.GetString("LoseChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Summary is used for retrieving and configuring end of session information..
        /// </summary>
        internal static string ModuleDescription {
            get {
                return ResourceManager.GetString("ModuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GameTech Edge Bingo System Session Summary Module.
        /// </summary>
        internal static string ModuleName {
            get {
                return ResourceManager.GetString("ModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No Sessions).
        /// </summary>
        internal static string NoSessions {
            get {
                return ResourceManager.GetString("NoSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalc_ulate.
        /// </summary>
        internal static string Recalculate {
            get {
                return ResourceManager.GetString("Recalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        internal static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and _generate.
        /// </summary>
        internal static string SaveGenerate {
            get {
                return ResourceManager.GetString("SaveGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved successfully.
        /// </summary>
        internal static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving session cost.
        /// </summary>
        internal static string SavingCost {
            get {
                return ResourceManager.GetString("SavingCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving session summary.
        /// </summary>
        internal static string SavingSummary {
            get {
                return ResourceManager.GetString("SavingSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server communication lost.
        ///
        ///Shutting down....
        /// </summary>
        internal static string ServerCommFailed {
            get {
                return ResourceManager.GetString("ServerCommFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Summary.
        /// </summary>
        internal static string SessionSummaryName {
            get {
                return ResourceManager.GetString("SessionSummaryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Session Summary....
        /// </summary>
        internal static string Starting {
            get {
                return ResourceManager.GetString("Starting", resourceCulture);
            }
        }
    }
}
